### ISSUE TITLE
Can't craft the GraviChestplate bug?

### ISSUE THREAD

**Issue by HaiderDK** [thebobsgammingnetwork/LapitosGalacticraft#10]
![bug](https://user-images.githubusercontent.com/34953835/59513353-f95a0b80-8eba-11e9-96bd-9ced0e46a9e7.PNG)

I got all the parts to craft it but it wont even show up in the crafting table. I even tried in single player and it does not work there either.

Is this intentional or a bug?

**Comment by oly2o6** [comment]
i took a shot at fixing it but ill have to redo it

**Comment by oly2o6** [comment]
issue fixed, added to pack within the next update (unless next update is a hotfix)
