### ISSUE TITLE
Mod suggestion: Some form of Magic mod

### ISSUE THREAD

**Issue by Shan0211** [thebobsgammingnetwork/LapitosGalacticraft#11]
I know when i played Lapitos back in 1.6.10 and i think 1.7.10 it had Magic mods (ars magica 2). Which isnt an option for 1.12.2 as far as i know. Would be great to add some sort of Magic Mod.
I know atleast 6-8 people have requested or asked for it a lot of times on the private server i run. 

I know thaumcraft for 1.12.2 is awesome, but any magic mod would be cool.

**Comment by minilolpor** [comment]
Agreed

**Comment by XPoTHackz** [comment]
^^
