### ISSUE TITLE
crashed on crafting 

### ISSUE THREAD

**Issue by DemonKingAkira** [thebobsgammingnetwork/LapitosGalacticraft#13]
https://paste.dimdev.org/itejipujod.mccrash

just was crafting planks, was crashed while crafting compressed cobblestone earlier. doesn't happen consistently. crafting anything sometimes crashes out of the blue.
deep dark also crashes on load.

**Comment by killzoms** [comment]
looks like dont use the vanilla recipe book...

**Comment by DemonKingAkira** [comment]
i dont use the book tho i use jei.

**Comment by borex99** [comment]
Crash occurs only if "Showing craftable" is enabled, regardless of whether the vanilla recipe book is displayed.
