### ISSUE TITLE
Can´t get my ic2 machines to work with Mekansm cables.

### ISSUE THREAD

**Issue by Gruppenfuehrer** [thebobsgammingnetwork/LapitosGalacticraft#14]
Hi!
There is a weird energy drain when I connect my ulitmate energy cube with elite cables to a BatBox/MFE/MFSU, or simply hook them up to my main power network, all the power gets instantly drained, while the IC2 machines do not get charged.

**Comment by Nbgreen** [comment]
The ic2 dev made it where his mod doesn’t accept energy from other mods not much I can do about this
