### ISSUE TITLE
Aluminum not generating properly

### ISSUE THREAD

**Issue by blivit** [thebobsgammingnetwork/LapitosGalacticraft#15]
Aluminum blocks are not generating properly.  Visibly look like tin blocks (white dots in stone block) rather than aluminum in previous versions (light blue color dots in stone block).   Also this version seems to spawn aluminum as rare as diamond blocks.  In previous versions Aluminum drops were far more prevalent.

**Comment by Nbgreen** [comment]
The aluminum spawn rate was increased in pack version 2.2.6
