### ISSUE TITLE
Infinite loading and other issues upon moon travel

### ISSUE THREAD

**Issue by davetassoni** [thebobsgammingnetwork/LapitosGalacticraft#16]
I successfully make a rocket, and i can get to space. once there, I do not have the prompt to make a space station (even though I have all the required materials, according to the wiki). I decide to go to the moon, and I am stuck on the loading screen for a very long time. The longest that I let this sit here is 30 minutes, and it still didn't leave the screen. So I close the game, and then reopen it, and die immediately. But I am on the Venus, not even the moon. After this, I decide to go to Venus, and the same thing happens, but then I open the game and am on Mercury instead. I checked the config files, and all of the dimension ids are properly assigned according to the Galacticraft wiki.

See log file below for server:

https://pastebin.com/T8LrTpnr

**Comment by Nbgreen** [comment]
This issue was fixed in the latest pack version

**Comment by davetassoni** [comment]
How do I update my dedicated server with version 2.2.5.1 without losing my data?

**Comment by Nbgreen** [comment]
You have two options if you haven’t edited any configs just drag you world folder into the new server build

**Comment by davetassoni** [comment]
Thanks for the help. I successfully updated the server to the newer build, and the issue does not occur anymore
