### ISSUE TITLE
Crash on using Deep Dark Portal

### ISSUE THREAD

**Issue by borex99** [thebobsgammingnetwork/LapitosGalacticraft#17]
Crash on using Deep Dark Portal
https://paste.dimdev.org/afitidanut.mccrash

**Comment by davetassoni** [comment]
https://wiki.micdoodle8.com/wiki/Compatibility

Hey, check out the galacticraft compatibility page. It details to download and add the Player-API-1.7.10-1.4.jar to your mods folder. This may fix the crash.

**Comment by Nbgreen** [comment]
The deep dark portal is disabled in the configs that is most likely what caused that issue

**Comment by borex99** [comment]
Deep Dark is disabled in config:`    B:"Deep Dark"=false`, but it can be crafted `    B:Teleporter=true`:
![image](https://user-images.githubusercontent.com/7602384/78864848-53d1e300-7a5e-11ea-805b-547e51c0bf45.png)
