### ISSUE TITLE
[MOD REQUEST] Applied Energistics 2

### ISSUE THREAD

**Issue by GabrielitoPL** [thebobsgammingnetwork/LapitosGalacticraft#20]
Mod Name?
Applied Energistics 2

URLs?
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

Description?
This mod helps in the storage of things, automation of crafting. self-processed and liquid etc. It would be very helpful for storage since the package does not include any until where I see, and if you have any problem with AE2 try with Logistics pipes which is almost the same. Either one would be great, thank you very much for your attention.

**Comment by Endercass** [comment]
we have refined storage which is pretty much the same sooo

**Comment by GabrielitoPL** [comment]
I did not realize. Thank you
