### ISSUE TITLE
Refined Iron Recipe Broken by adding Varied Commodities

### ISSUE THREAD

**Issue by MrKiel** [thebobsgammingnetwork/LapitosGalacticraft#21]
As per title. 

The addition of Varied Commodities broke the recipe for Refined Iron. 
Can the mod either be removed or a workaround recipe be added please?

**Comment by CommanderLouiz** [comment]
A workaround recipe is added server-side. Two Refined Iron in the Top-left and Top-middle of a crafting table will yield two Mekanism Steel Ingots, and two of any steel in the Top-left and Top-middle will yield two refined iron.

It will need a client update to appear in JEI and singleplayer, but it works on the server.
