### ISSUE TITLE
Lapitos Mod Suggestion

### ISSUE THREAD

**Issue by VexyChan** [thebobsgammingnetwork/LapitosGalacticraft#5]
Mod Name: thaumcraft
Link to mod: https://www.curseforge.com/minecraft/mc-mods/thaumcraft
Reasoning: It would help with lapitos end game and be a good substitute for ars magic

**Comment by Shan0211** [comment]
i 100% agree! Would be awesome to integrate with lapitos

**Comment by GabrielitoPL** [comment]
Good morning, excuse me what happened to this mod, it would be great if they added it to give a magical atmosphere to the modpack, tubieorn herrors when integrating it or did I miss something ?. I was also about to suggest this mod.
