### ISSUE TITLE
Quantum Armor provides close to no protection

### ISSUE THREAD

**Issue by Teo813** [thebobsgammingnetwork/LapitosGalacticraft#9]
Fluxed electrum armor is able to sustain an empowered quiver and empowered flux bow and not take a single heart while a power 5 flux bow only is enough to instantly kill a quantum suited person.

**Comment by oly2o6** [comment]
quantum hasnt had an configs set to it to buff the protection this will be changed in following updates and i will notify you when this happens

**Comment by Teo813** [comment]
Thank you for telling me

**Comment by HaiderDK** [comment]
Quantum armor needs a buff, it's much more harder to make than power armor which is better than quantum armor atm.

**Comment by oly2o6** [comment]
As I said it will be looked into when we have the chance
